/**
 * Seed script for All Window Door Parts product catalog.
 * SKU format: AWDP-XX-XXXX
 * Encoding table: P=1, R=2, O=3, F=4, I=5, T=6, A=7, B=8, L=9, E=0
 * Suppliers: Biltbest (BB), Truth/Entrygard (TH), Oldach (OL), Strybuc (SB)
 * Strybuc prices are marked up 35-50% as they are the distributor source.
 */

import { db } from "@workspace/db";
import { productsTable, categoriesTable } from "@workspace/db/schema";
import { sql } from "drizzle-orm";

// Markup helper for Strybuc products
function strybucMarkup(cost: number, markup = 0.42): number {
  return Math.round(cost * (1 + markup) * 100) / 100;
}

const categories = [
  { name: "Window Operators & Cranks", slug: "window-operators", description: "Casement, awning, and jalousie window operators and cranks for all major brands.", imageUrl: "https://www.strybuc.com/images/categories/operators.jpg" },
  { name: "Window Locks & Latches", slug: "window-locks", description: "Sash locks, cam locks, and latching hardware for single and double-hung windows.", imageUrl: "https://www.strybuc.com/images/categories/locks.jpg" },
  { name: "Window Balances", slug: "window-balances", description: "Spiral, block-and-tackle, and channel balances for proper window operation.", imageUrl: "https://www.strybuc.com/images/categories/balances.jpg" },
  { name: "Window Screens & Frames", slug: "window-screens", description: "Screen frames, spline, mesh, and screen hardware for all window types.", imageUrl: "https://www.strybuc.com/images/categories/screens.jpg" },
  { name: "Door Hardware", slug: "door-hardware", description: "Entry, patio, and storm door hardware including handles, hinges, and closers.", imageUrl: "https://www.strybuc.com/images/categories/door-hardware.jpg" },
  { name: "Door Locks & Deadbolts", slug: "door-locks", description: "Mortise locks, multi-point locking systems, and deadbolts for all door types.", imageUrl: "https://www.strybuc.com/images/categories/door-locks.jpg" },
  { name: "Weatherstripping & Seals", slug: "weatherstripping", description: "Foam, felt, silicone, and pile weatherstripping for windows and doors.", imageUrl: "https://www.strybuc.com/images/categories/weatherstrip.jpg" },
  { name: "Hinges & Pivots", slug: "hinges", description: "Butt hinges, continuous hinges, and pivot hardware for doors and windows.", imageUrl: "https://www.strybuc.com/images/categories/hinges.jpg" },
  { name: "Rollers & Guides", slug: "rollers", description: "Patio door rollers, sliding window rollers, and guide hardware.", imageUrl: "https://www.strybuc.com/images/categories/rollers.jpg" },
  { name: "Sash & Frame Parts", slug: "sash-parts", description: "Corner keys, frame joiners, sash lifts, and window frame components.", imageUrl: "https://www.strybuc.com/images/categories/sash.jpg" },
];

// AWDP SKU system: AWDP-[2-digit cat code]-[4-digit product code]
// Category codes: 10=Operators, 20=Locks, 30=Balances, 40=Screens, 50=Door HW, 60=Door Locks, 70=Weatherstrip, 80=Hinges, 90=Rollers, 11=Sash
const products = [
  // === WINDOW OPERATORS (cat 10) - Truth Hardware / Biltbest ===
  {
    sku: "AWDP-10-1001",
    name: "Truth Entrygard Casement Operator - Right Hand",
    description: "Genuine Truth Entrygard right-hand casement window operator. Fits most Truth and Biltbest casement windows manufactured after 1990. Heavy-duty zinc alloy construction with smooth operation. Compatible with Truth operator handles and covers.",
    price: 38.95,
    originalPrice: null,
    category: "Window Operators & Cranks",
    subcategory: "Casement Operators",
    supplier: "Truth/Entrygard",
    inStock: true,
    imageUrl: "https://www.truthhardware.com/sites/default/files/2022-07/36.19-1.jpg",
    tags: ["casement", "operator", "truth", "entrygard", "right-hand"],
    specifications: { "Hand": "Right", "Finish": "White", "Material": "Die-cast zinc", "Hinge Pad Width": "1-3/4\"", "Arm Length": "9\"" },
    compatibleBrands: ["Truth Hardware", "Biltbest", "Pella", "Weather Shield"],
  },
  {
    sku: "AWDP-10-1002",
    name: "Truth Entrygard Casement Operator - Left Hand",
    description: "Genuine Truth Entrygard left-hand casement window operator. Matches right-hand version AWDP-10-1001. Heavy-duty zinc alloy for long-lasting smooth operation on casement windows.",
    price: 38.95,
    originalPrice: null,
    category: "Window Operators & Cranks",
    subcategory: "Casement Operators",
    supplier: "Truth/Entrygard",
    inStock: true,
    imageUrl: "https://www.truthhardware.com/sites/default/files/2022-07/36.19-1.jpg",
    tags: ["casement", "operator", "truth", "entrygard", "left-hand"],
    specifications: { "Hand": "Left", "Finish": "White", "Material": "Die-cast zinc", "Hinge Pad Width": "1-3/4\"", "Arm Length": "9\"" },
    compatibleBrands: ["Truth Hardware", "Biltbest", "Pella", "Weather Shield"],
  },
  {
    sku: "AWDP-10-1003",
    name: "Biltbest 4-Bar Casement Hinge Arm Assembly",
    description: "OEM Biltbest 4-bar casement hinge arm assembly for smooth casement window opening. Full stainless steel construction resists corrosion. Replacement for worn or broken scissor arms on Biltbest casement windows.",
    price: 29.50,
    originalPrice: null,
    category: "Window Operators & Cranks",
    subcategory: "Hinge Arms",
    supplier: "Biltbest",
    inStock: true,
    imageUrl: "https://images.thdstatic.com/productImages/d42accd5-0b35-4e9c-aabf-2e4fe96dce47/svn/prime-line-casement-window-operators-h-3805-64_600.jpg",
    tags: ["casement", "hinge arm", "biltbest", "4-bar"],
    specifications: { "Material": "Stainless steel", "Arm Style": "4-bar scissor", "Finish": "Satin" },
    compatibleBrands: ["Biltbest", "Norco"],
  },
  {
    sku: "AWDP-10-1004",
    name: "Strybuc Casement Window Operator - Roto Style, Right Hand",
    description: "Universal roto-style right-hand casement operator. Fits most single-arm casement operators from the 1970s-2000s. Worm gear drive for positive control. Replaces Anderson, Pella, and many generic brands.",
    price: strybucMarkup(19.95),
    originalPrice: 19.95,
    category: "Window Operators & Cranks",
    subcategory: "Casement Operators",
    supplier: "Strybuc",
    inStock: true,
    imageUrl: "https://www.strybuc.com/media/catalog/product/cache/1/image/700x700/9df78eab33525d08d6e5fb8d27136e95/s/b/sb-op-roto-rh.jpg",
    tags: ["casement", "operator", "roto", "right-hand", "universal"],
    specifications: { "Hand": "Right", "Finish": "White", "Drive": "Worm gear", "Mounting Holes": "2" },
    compatibleBrands: ["Anderson", "Pella", "Hurd", "Marvin"],
  },
  {
    sku: "AWDP-10-1005",
    name: "Awning Window Operator - Dual Arm, White",
    description: "Heavy-duty dual arm awning window operator for 16\" to 36\" wide awning windows. Smooth worm gear mechanism with non-slip handle. Fits most Truth and Biltbest awning windows.",
    price: strybucMarkup(24.50),
    originalPrice: 24.50,
    category: "Window Operators & Cranks",
    subcategory: "Awning Operators",
    supplier: "Strybuc",
    inStock: true,
    imageUrl: "https://www.strybuc.com/media/catalog/product/cache/1/image/700x700/9df78eab33525d08d6e5fb8d27136e95/a/w/aw-op-dual.jpg",
    tags: ["awning", "operator", "dual arm", "white"],
    specifications: { "Type": "Dual arm", "Finish": "White", "Window Width Range": "16\"-36\"", "Mounting": "Surface mount" },
    compatibleBrands: ["Truth Hardware", "Biltbest", "Peachtree"],
  },
  {
    sku: "AWDP-10-1006",
    name: "Window Operator Crank Handle - 9/16\" Spline",
    description: "Replacement crank handle for casement and awning window operators. 9/16\" spline drive fits most Truth Entrygard operators. Low-profile design. Available in white.",
    price: strybucMarkup(8.95),
    originalPrice: 8.95,
    category: "Window Operators & Cranks",
    subcategory: "Crank Handles",
    supplier: "Strybuc",
    inStock: true,
    imageUrl: "https://www.strybuc.com/media/catalog/product/cache/1/image/700x700/9df78eab33525d08d6e5fb8d27136e95/c/r/crank-handle-9-16.jpg",
    tags: ["crank handle", "operator handle", "9/16 spline"],
    specifications: { "Spline Size": "9/16\"", "Finish": "White", "Material": "Impact-resistant plastic" },
    compatibleBrands: ["Truth Hardware", "Biltbest", "General Windows"],
  },

  // === WINDOW LOCKS (cat 20) ===
  {
    sku: "AWDP-20-2001",
    name: "Sash Lock & Keeper - Double-Hung Windows, White",
    description: "Diecast sash lock and keeper set for single and double-hung windows. Universal fit with 1-3/4\" screw hole spacing. Cam-action lock provides positive close. Replaces most common sash locks on the market.",
    price: strybucMarkup(12.50),
    originalPrice: 12.50,
    category: "Window Locks & Latches",
    subcategory: "Sash Locks",
    supplier: "Strybuc",
    inStock: true,
    imageUrl: "https://www.strybuc.com/media/catalog/product/cache/1/image/700x700/9df78eab33525d08d6e5fb8d27136e95/s/a/sash-lock-white.jpg",
    tags: ["sash lock", "keeper", "double hung", "white", "cam lock"],
    specifications: { "Hole Spacing": "1-3/4\"", "Finish": "White", "Material": "Die-cast zinc", "Keeper Included": "Yes" },
    compatibleBrands: ["Most brands"],
  },
  {
    sku: "AWDP-20-2002",
    name: "Casement Window Sweep Lock & Keeper - Truth Hardware",
    description: "Genuine Truth Hardware casement sweep lock with keeper. Easy one-handed operation with over-center locking action. Ideal for casement and awning windows requiring a tight weatherseal.",
    price: 18.75,
    originalPrice: null,
    category: "Window Locks & Latches",
    subcategory: "Casement Locks",
    supplier: "Truth/Entrygard",
    inStock: true,
    imageUrl: "https://www.truthhardware.com/sites/default/files/2022-07/35.06-1.jpg",
    tags: ["casement lock", "sweep lock", "truth hardware", "keeper"],
    specifications: { "Type": "Sweep lock", "Finish": "White", "Action": "Over-center", "Hand": "Universal" },
    compatibleBrands: ["Truth Hardware", "Biltbest", "Norco"],
  },
  {
    sku: "AWDP-20-2003",
    name: "Sliding Window Latch - Aluminum, Universal",
    description: "Universal sliding window latch for horizontal sliding windows. Spring-loaded catch with a smooth operation. Fits 3/4\" to 1\" frame thickness. Aluminum construction for lasting performance.",
    price: strybucMarkup(9.75),
    originalPrice: 9.75,
    category: "Window Locks & Latches",
    subcategory: "Sliding Latches",
    supplier: "Strybuc",
    inStock: true,
    imageUrl: "https://www.strybuc.com/media/catalog/product/cache/1/image/700x700/9df78eab33525d08d6e5fb8d27136e95/s/l/sliding-win-latch.jpg",
    tags: ["sliding window", "latch", "aluminum", "universal"],
    specifications: { "Frame Thickness": "3/4\" - 1\"", "Material": "Aluminum", "Finish": "Mill aluminum" },
    compatibleBrands: ["Most sliding window brands"],
  },

  // === WINDOW BALANCES (cat 30) ===
  {
    sku: "AWDP-30-3001",
    name: "Spiral Window Balance - 15/32\" x 24\", White",
    description: "15/32\" diameter x 24\" long spiral balance for single and double-hung windows. Tip size B (bronze). Pre-tensioned from factory. Replaces most spiral balances in windows made since 1985.",
    price: strybucMarkup(11.50),
    originalPrice: 11.50,
    category: "Window Balances",
    subcategory: "Spiral Balances",
    supplier: "Strybuc",
    inStock: true,
    imageUrl: "https://www.strybuc.com/media/catalog/product/cache/1/image/700x700/9df78eab33525d08d6e5fb8d27136e95/s/p/spiral-balance-24.jpg",
    tags: ["spiral balance", "window balance", "15/32", "24 inch"],
    specifications: { "Diameter": "15/32\"", "Length": "24\"", "Tip": "B (Bronze)", "Color": "White" },
    compatibleBrands: ["Caldwell", "Biltbest", "Andersen", "Pella"],
  },
  {
    sku: "AWDP-30-3002",
    name: "Block & Tackle Window Balance - 2-Wheel, Series 600",
    description: "Series 600 block-and-tackle balance with 2-wheel pulley. For windows 15-30 lbs. Stamped steel housing with nylon pulleys. Used in most major window brands from 1990 onward.",
    price: strybucMarkup(14.25),
    originalPrice: 14.25,
    category: "Window Balances",
    subcategory: "Block & Tackle Balances",
    supplier: "Strybuc",
    inStock: true,
    imageUrl: "https://www.strybuc.com/media/catalog/product/cache/1/image/700x700/9df78eab33525d08d6e5fb8d27136e95/b/l/bt-balance-600.jpg",
    tags: ["block tackle", "window balance", "series 600", "2-wheel"],
    specifications: { "Series": "600", "Wheels": "2", "Sash Weight Range": "15-30 lbs", "Material": "Steel housing, nylon pulleys" },
    compatibleBrands: ["Andersen", "Pella", "Hurd", "Marvin", "Eagle"],
  },
  {
    sku: "AWDP-30-3003",
    name: "Channel Balance - 3/4\" x 36\", White",
    description: "Channel window balance 3/4\" wide x 36\" long. Fits in channel routed into sash sides. Includes clips. Heavy-duty coil spring, 20-35 lb capacity. Replaces worn or broken channel balances in older double-hung windows.",
    price: strybucMarkup(16.50),
    originalPrice: 16.50,
    category: "Window Balances",
    subcategory: "Channel Balances",
    supplier: "Strybuc",
    inStock: true,
    imageUrl: "https://www.strybuc.com/media/catalog/product/cache/1/image/700x700/9df78eab33525d08d6e5fb8d27136e95/c/h/channel-balance-36.jpg",
    tags: ["channel balance", "window balance", "36 inch", "double hung"],
    specifications: { "Width": "3/4\"", "Length": "36\"", "Capacity": "20-35 lbs", "Color": "White" },
    compatibleBrands: ["Pozzi", "Semco", "Crestline"],
  },

  // === WINDOW SCREENS (cat 40) ===
  {
    sku: "AWDP-40-4001",
    name: "Window Screen Spline - 0.140\" Round, 25 ft Roll",
    description: "Round vinyl window screen spline 0.140\" (9/64\") diameter. 25-foot roll. Works with standard aluminum or vinyl screen frames. Easy to install with a spline roller tool.",
    price: strybucMarkup(4.95),
    originalPrice: 4.95,
    category: "Window Screens & Frames",
    subcategory: "Screen Spline",
    supplier: "Strybuc",
    inStock: true,
    imageUrl: "https://www.strybuc.com/media/catalog/product/cache/1/image/700x700/9df78eab33525d08d6e5fb8d27136e95/s/c/screen-spline-140.jpg",
    tags: ["screen spline", "vinyl spline", "0.140", "window screen"],
    specifications: { "Diameter": "0.140\" (9/64\")", "Length": "25 ft", "Material": "Vinyl", "Color": "Gray" },
    compatibleBrands: ["Universal fit"],
  },
  {
    sku: "AWDP-40-4002",
    name: "Screen Door & Window Fiberglass Mesh - 36\" x 84\"",
    description: "Premium fiberglass window and door screen mesh. 36\" x 84\" roll. 18x16 mesh count. Charcoal color for maximum outward visibility. Does not rust or corrode. Easy to cut and install.",
    price: strybucMarkup(14.75),
    originalPrice: 14.75,
    category: "Window Screens & Frames",
    subcategory: "Screen Mesh",
    supplier: "Strybuc",
    inStock: true,
    imageUrl: "https://www.strybuc.com/media/catalog/product/cache/1/image/700x700/9df78eab33525d08d6e5fb8d27136e95/f/i/fiberglass-mesh-36x84.jpg",
    tags: ["screen mesh", "fiberglass mesh", "window screen", "36x84"],
    specifications: { "Width": "36\"", "Length": "84\"", "Mesh Count": "18x16", "Color": "Charcoal", "Material": "Fiberglass" },
    compatibleBrands: ["Universal fit"],
  },
  {
    sku: "AWDP-40-4003",
    name: "Sliding Screen Door Roller - Adjustable Height",
    description: "Replacement adjustable roller for sliding screen doors. Fits most aluminum frame screen doors. Height adjustable from 1\" to 1-1/2\" with set screw. Sold in pairs.",
    price: strybucMarkup(7.95),
    originalPrice: 7.95,
    category: "Window Screens & Frames",
    subcategory: "Screen Rollers",
    supplier: "Strybuc",
    inStock: true,
    imageUrl: "https://www.strybuc.com/media/catalog/product/cache/1/image/700x700/9df78eab33525d08d6e5fb8d27136e95/s/c/screen-door-roller.jpg",
    tags: ["screen door roller", "sliding screen", "adjustable"],
    specifications: { "Wheel Material": "Nylon", "Height Adjustment": "1\" - 1-1/2\"", "Sold As": "Pair" },
    compatibleBrands: ["Most sliding screen doors"],
  },

  // === DOOR HARDWARE (cat 50) ===
  {
    sku: "AWDP-50-5001",
    name: "Patio Door Handle Set - Interior & Exterior, White",
    description: "Complete patio door handle set with interior and exterior handles. White finish. Fits most aluminum and vinyl sliding patio doors with 3-1/2\" hole spacing. Includes all mounting hardware.",
    price: strybucMarkup(39.95),
    originalPrice: 39.95,
    category: "Door Hardware",
    subcategory: "Patio Door Handles",
    supplier: "Strybuc",
    inStock: true,
    imageUrl: "https://www.strybuc.com/media/catalog/product/cache/1/image/700x700/9df78eab33525d08d6e5fb8d27136e95/p/a/patio-door-handle-white.jpg",
    tags: ["patio door", "handle set", "sliding door", "white"],
    specifications: { "Hole Spacing": "3-1/2\"", "Finish": "White", "Includes": "Interior handle, exterior pull, hardware", "Backset": "1-3/4\"" },
    compatibleBrands: ["Peachtree", "Crestline", "General Products"],
  },
  {
    sku: "AWDP-50-5002",
    name: "Storm Door Closer - Heavy Duty, Pneumatic",
    description: "Heavy-duty pneumatic storm door closer with adjustable closing speed. Fits doors 32\" to 36\" wide. Matte black finish. Includes all mounting hardware. Rated for 10-year service life.",
    price: strybucMarkup(28.50),
    originalPrice: 28.50,
    category: "Door Hardware",
    subcategory: "Door Closers",
    supplier: "Strybuc",
    inStock: true,
    imageUrl: "https://www.strybuc.com/media/catalog/product/cache/1/image/700x700/9df78eab33525d08d6e5fb8d27136e95/s/t/storm-door-closer-blk.jpg",
    tags: ["storm door", "door closer", "pneumatic", "heavy duty"],
    specifications: { "Door Width": "32\" - 36\"", "Finish": "Matte black", "Speed": "Adjustable", "Rating": "10-year" },
    compatibleBrands: ["Universal fit"],
  },
  {
    sku: "AWDP-50-5003",
    name: "Oldach Steel Door Hinge - 4\" x 4\", Ball Bearing",
    description: "Oldach heavy-duty 4\" x 4\" steel door hinge with NRP (non-removable pin) for exterior security doors. Ball-bearing knuckles for smooth, quiet operation. Primed for paint.",
    price: 14.95,
    originalPrice: null,
    category: "Door Hardware",
    subcategory: "Door Hinges",
    supplier: "Oldach",
    inStock: true,
    imageUrl: "https://images.thdstatic.com/productImages/8e7c2e00-2f03-4ef0-98af-e1c024b8ee06/svn/prime-line-door-hinges-n-7444-64_600.jpg",
    tags: ["door hinge", "steel hinge", "ball bearing", "4x4", "NRP"],
    specifications: { "Size": "4\" x 4\"", "Material": "Steel", "Knuckle": "Ball bearing", "Pin": "Non-removable (NRP)", "Finish": "Primed" },
    compatibleBrands: ["Universal - fits standard door frames"],
  },
  {
    sku: "AWDP-50-5004",
    name: "Sliding Patio Door Foot Bolt / Security Bar",
    description: "Floor-mount security bar and foot bolt for sliding patio doors. Aluminum construction. Blocks door from being lifted or forced open. Installs in track without drilling. Adjustable to fit most tracks.",
    price: strybucMarkup(11.25),
    originalPrice: 11.25,
    category: "Door Hardware",
    subcategory: "Security Hardware",
    supplier: "Strybuc",
    inStock: true,
    imageUrl: "https://www.strybuc.com/media/catalog/product/cache/1/image/700x700/9df78eab33525d08d6e5fb8d27136e95/p/a/patio-security-bar.jpg",
    tags: ["patio door", "security bar", "foot bolt", "sliding door security"],
    specifications: { "Material": "Aluminum", "Installation": "No drilling required", "Adjustable": "Yes", "Color": "Mill aluminum" },
    compatibleBrands: ["Universal sliding patio doors"],
  },

  // === DOOR LOCKS (cat 60) ===
  {
    sku: "AWDP-60-6001",
    name: "Patio Door Mortise Lock - 3-Point, Multi-Point",
    description: "Multi-point patio door mortise lock body with 3-point locking. Works with standard patio door handles. Sold as lock body only. Backset 1-3/4\". Fits most Peachtree, Crestline, and vinyl patio doors.",
    price: strybucMarkup(44.95),
    originalPrice: 44.95,
    category: "Door Locks & Deadbolts",
    subcategory: "Mortise Locks",
    supplier: "Strybuc",
    inStock: true,
    imageUrl: "https://www.strybuc.com/media/catalog/product/cache/1/image/700x700/9df78eab33525d08d6e5fb8d27136e95/m/o/mortise-lock-3pt.jpg",
    tags: ["mortise lock", "3-point lock", "patio door", "multi-point"],
    specifications: { "Points": "3", "Backset": "1-3/4\"", "Latch": "Includes", "Material": "Zinc" },
    compatibleBrands: ["Peachtree", "Crestline", "Semco", "Comfort Line"],
  },
  {
    sku: "AWDP-60-6002",
    name: "Oldach Entry Door Multi-Point Lock System",
    description: "Complete multi-point locking system for inswing entry doors. Three hooks engage simultaneously with one handle turn. Dramatically improves door security and weatherseal. Includes installation template.",
    price: 89.95,
    originalPrice: null,
    category: "Door Locks & Deadbolts",
    subcategory: "Multi-Point Locks",
    supplier: "Oldach",
    inStock: true,
    imageUrl: "https://images.thdstatic.com/productImages/3c0e8c96-c16e-4f96-aef4-26a2ac2e5f5d/svn/bright-chrome-door-locks-mpl-32d-c-64_600.jpg",
    tags: ["multi-point lock", "entry door", "security", "oldach"],
    specifications: { "Points": "3", "Door Swing": "Inswing", "Included": "Lock body, hooks, strike, hardware", "Handle": "Sold separately" },
    compatibleBrands: ["Oldach", "Peachtree", "Weather Shield"],
  },

  // === WEATHERSTRIPPING (cat 70) ===
  {
    sku: "AWDP-70-7001",
    name: "Door Bottom Sweep - Aluminum w/ Vinyl Insert, 36\"",
    description: "Heavy-duty aluminum door bottom sweep with vinyl sealing insert. 36\" length, cuts to fit. Automatic door bottom sweep with spring-lift mechanism raises when door is open, seals when closed. Blocks drafts, water, insects.",
    price: strybucMarkup(18.95),
    originalPrice: 18.95,
    category: "Weatherstripping & Seals",
    subcategory: "Door Sweeps",
    supplier: "Strybuc",
    inStock: true,
    imageUrl: "https://www.strybuc.com/media/catalog/product/cache/1/image/700x700/9df78eab33525d08d6e5fb8d27136e95/d/o/door-sweep-36.jpg",
    tags: ["door sweep", "door bottom", "weatherstrip", "36 inch"],
    specifications: { "Length": "36\"", "Material": "Aluminum/Vinyl", "Mechanism": "Automatic spring-lift", "Finish": "Aluminum" },
    compatibleBrands: ["Universal - cuts to fit"],
  },
  {
    sku: "AWDP-70-7002",
    name: "Window Pile Weatherstripping - 3/8\" x 3/8\", 50 ft",
    description: "Self-adhesive pile weatherstripping for windows and sliding doors. 3/8\" x 3/8\" with polypropylene pile. 50-foot roll. Excellent for reducing air infiltration and noise around sliding windows and doors.",
    price: strybucMarkup(13.25),
    originalPrice: 13.25,
    category: "Weatherstripping & Seals",
    subcategory: "Pile Weatherstrip",
    supplier: "Strybuc",
    inStock: true,
    imageUrl: "https://www.strybuc.com/media/catalog/product/cache/1/image/700x700/9df78eab33525d08d6e5fb8d27136e95/p/i/pile-weatherstrip-50ft.jpg",
    tags: ["pile weatherstrip", "sliding window", "weathersealing", "self adhesive"],
    specifications: { "Height": "3/8\"", "Width": "3/8\"", "Length": "50 ft", "Backing": "Self-adhesive", "Color": "Gray" },
    compatibleBrands: ["Universal sliding windows and doors"],
  },
  {
    sku: "AWDP-70-7003",
    name: "Foam Tape Weatherstrip - 1/2\" x 3/4\", 17 ft",
    description: "Closed-cell foam weatherstrip tape for sealing gaps around windows and doors. 1/2\" thick x 3/4\" wide. Self-adhesive backing. UV and moisture resistant. 17-foot roll.",
    price: strybucMarkup(6.50),
    originalPrice: 6.50,
    category: "Weatherstripping & Seals",
    subcategory: "Foam Weatherstrip",
    supplier: "Strybuc",
    inStock: true,
    imageUrl: "https://www.strybuc.com/media/catalog/product/cache/1/image/700x700/9df78eab33525d08d6e5fb8d27136e95/f/o/foam-tape-ws.jpg",
    tags: ["foam weatherstrip", "tape", "self adhesive", "door seal"],
    specifications: { "Thickness": "1/2\"", "Width": "3/4\"", "Length": "17 ft", "Material": "Closed-cell foam", "Backing": "Acrylic self-adhesive" },
    compatibleBrands: ["Universal"],
  },

  // === HINGES & PIVOTS (cat 80) ===
  {
    sku: "AWDP-80-8001",
    name: "Casement Window Hinge - Stainless Steel, 11\" Arm",
    description: "Heavy-duty stainless steel casement window hinge with 11\" arm. Provides maximum 90-degree opening. Friction stay prevents slamming. For wooden or aluminum casement frames. Sold as single hinge.",
    price: 24.95,
    originalPrice: null,
    category: "Hinges & Pivots",
    subcategory: "Casement Hinges",
    supplier: "Truth/Entrygard",
    inStock: true,
    imageUrl: "https://www.truthhardware.com/sites/default/files/2022-07/33.09-1.jpg",
    tags: ["casement hinge", "friction stay", "stainless steel", "11 inch"],
    specifications: { "Arm Length": "11\"", "Material": "Stainless steel", "Opening": "90 degrees max", "Friction Stay": "Yes" },
    compatibleBrands: ["Truth Hardware", "Biltbest", "General Windows"],
  },
  {
    sku: "AWDP-80-8002",
    name: "Continuous Piano Hinge - Aluminum, 72\", Full Mortise",
    description: "Full-length aluminum piano hinge (continuous hinge). 72\" long x 1-1/2\" leaf. For storm doors, screen doors, cabinet doors. Full mortise style. Cut to any length with a hacksaw.",
    price: strybucMarkup(29.95),
    originalPrice: 29.95,
    category: "Hinges & Pivots",
    subcategory: "Piano Hinges",
    supplier: "Strybuc",
    inStock: true,
    imageUrl: "https://www.strybuc.com/media/catalog/product/cache/1/image/700x700/9df78eab33525d08d6e5fb8d27136e95/p/i/piano-hinge-72.jpg",
    tags: ["piano hinge", "continuous hinge", "aluminum", "72 inch"],
    specifications: { "Length": "72\"", "Leaf Width": "1-1/2\" each side", "Material": "Aluminum", "Style": "Full mortise" },
    compatibleBrands: ["Universal - cut to fit"],
  },

  // === ROLLERS & GUIDES (cat 90) ===
  {
    sku: "AWDP-90-9001",
    name: "Patio Door Roller Assembly - Tandem, Adjustable",
    description: "Tandem patio door roller assembly with two 1-1/4\" diameter wheels. Adjustable from 3/4\" to 1-1/8\" to fit different track depths. For aluminum and vinyl sliding patio doors. Smooth nylon wheels on steel housing.",
    price: strybucMarkup(22.50),
    originalPrice: 22.50,
    category: "Rollers & Guides",
    subcategory: "Patio Door Rollers",
    supplier: "Strybuc",
    inStock: true,
    imageUrl: "https://www.strybuc.com/media/catalog/product/cache/1/image/700x700/9df78eab33525d08d6e5fb8d27136e95/p/a/patio-door-roller-tandem.jpg",
    tags: ["patio door roller", "tandem roller", "sliding door", "adjustable"],
    specifications: { "Wheel Diameter": "1-1/4\"", "Wheel Count": "2 (tandem)", "Adjustment": "3/4\" - 1-1/8\"", "Housing": "Steel" },
    compatibleBrands: ["Peachtree", "Crestline", "Philips", "Most patio doors"],
  },
  {
    sku: "AWDP-90-9002",
    name: "Sliding Window Roller - 3/4\" Wheel, Nylon",
    description: "Replacement sliding window roller with 3/4\" nylon wheel. Flat-bottom housing mounts on frame bottom. Spring-tensioned for consistent track contact. Works with most aluminum horizontal sliding windows.",
    price: strybucMarkup(5.50),
    originalPrice: 5.50,
    category: "Rollers & Guides",
    subcategory: "Window Rollers",
    supplier: "Strybuc",
    inStock: true,
    imageUrl: "https://www.strybuc.com/media/catalog/product/cache/1/image/700x700/9df78eab33525d08d6e5fb8d27136e95/s/l/sliding-win-roller.jpg",
    tags: ["window roller", "sliding window", "nylon roller", "3/4 inch"],
    specifications: { "Wheel Diameter": "3/4\"", "Wheel Material": "Nylon", "Housing": "Flat-bottom", "Spring": "Yes" },
    compatibleBrands: ["Most aluminum sliding windows"],
  },

  // === SASH PARTS (cat 11) ===
  {
    sku: "AWDP-11-1101",
    name: "Window Corner Key - Aluminum Frame, 90 Degree",
    description: "Aluminum corner key for 90-degree window frame corners. Fits most standard aluminum window frame extrusions. Sold in packs of 4. Ideal for rebuilding or repairing aluminum sash and frame corners.",
    price: strybucMarkup(8.25),
    originalPrice: 8.25,
    category: "Sash & Frame Parts",
    subcategory: "Corner Keys",
    supplier: "Strybuc",
    inStock: true,
    imageUrl: "https://www.strybuc.com/media/catalog/product/cache/1/image/700x700/9df78eab33525d08d6e5fb8d27136e95/c/o/corner-key-al.jpg",
    tags: ["corner key", "aluminum frame", "sash repair", "window frame"],
    specifications: { "Angle": "90 degrees", "Material": "Aluminum", "Pack": "4 pieces" },
    compatibleBrands: ["Most aluminum window frames"],
  },
  {
    sku: "AWDP-11-1102",
    name: "Sash Lift - Recessed Pull, White - 2 Pack",
    description: "Recessed sash lift pulls for double-hung windows. Mounts flush into sash rail so there is nothing to snag on blinds. White finish. Pack of 2 pulls with mounting screws included.",
    price: strybucMarkup(6.95),
    originalPrice: 6.95,
    category: "Sash & Frame Parts",
    subcategory: "Sash Lifts",
    supplier: "Strybuc",
    inStock: true,
    imageUrl: "https://www.strybuc.com/media/catalog/product/cache/1/image/700x700/9df78eab33525d08d6e5fb8d27136e95/s/a/sash-lift-recessed.jpg",
    tags: ["sash lift", "recessed pull", "double hung", "white"],
    specifications: { "Type": "Recessed", "Finish": "White", "Pack": "2 pieces", "Includes": "Mounting screws" },
    compatibleBrands: ["Universal double-hung windows"],
  },
  {
    sku: "AWDP-11-1103",
    name: "Biltbest Tilt Latch - Snap In, Single-Hung Window",
    description: "Genuine Biltbest snap-in tilt latch for single-hung tilt windows. Allows sash to tilt in for easy cleaning. Simple snap-in installation — no tools needed. White finish. Sold as pair.",
    price: 15.95,
    originalPrice: null,
    category: "Sash & Frame Parts",
    subcategory: "Tilt Latches",
    supplier: "Biltbest",
    inStock: true,
    imageUrl: "https://images.thdstatic.com/productImages/01cf2a67-4f5e-46b9-86d4-5a8c93a3e78b/svn/white-prime-line-window-latches-u-9979-64_600.jpg",
    tags: ["tilt latch", "biltbest", "single hung", "tilt window"],
    specifications: { "Type": "Snap-in", "Finish": "White", "Sold As": "Pair", "Installation": "No tools required" },
    compatibleBrands: ["Biltbest", "Crestline", "Comfort Line"],
  },
];

async function seed() {
  console.log("Clearing existing data...");
  await db.delete(productsTable);
  await db.delete(categoriesTable);

  console.log("Seeding categories...");
  await db.insert(categoriesTable).values(categories);
  console.log(`  Inserted ${categories.length} categories`);

  console.log("Seeding products...");
  // Insert in batches of 10
  for (let i = 0; i < products.length; i += 10) {
    const batch = products.slice(i, i + 10);
    await db.insert(productsTable).values(
      batch.map((p) => ({
        ...p,
        price: String(p.price),
        originalPrice: p.originalPrice !== null ? String(p.originalPrice) : null,
      }))
    );
  }
  console.log(`  Inserted ${products.length} products`);
  console.log("Seed complete!");
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
